// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record_ingest.proto

package io.debezium.server.iceberg.rpc;

public final class RecordIngest {
  private RecordIngest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordIngestRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.debezium.server.iceberg.rpc.RecordIngestRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string messages = 1;</code>
     * @return A list containing the messages.
     */
    java.util.List<java.lang.String>
        getMessagesList();
    /**
     * <code>repeated string messages = 1;</code>
     * @return The count of messages.
     */
    int getMessagesCount();
    /**
     * <code>repeated string messages = 1;</code>
     * @param index The index of the element to return.
     * @return The messages at the given index.
     */
    java.lang.String getMessages(int index);
    /**
     * <code>repeated string messages = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the messages at the given index.
     */
    com.google.protobuf.ByteString
        getMessagesBytes(int index);
  }
  /**
   * <pre>
   * The request message containing an array of strings.
   * </pre>
   *
   * Protobuf type {@code io.debezium.server.iceberg.rpc.RecordIngestRequest}
   */
  public static final class RecordIngestRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.debezium.server.iceberg.rpc.RecordIngestRequest)
      RecordIngestRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordIngestRequest.newBuilder() to construct.
    private RecordIngestRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordIngestRequest() {
      messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecordIngestRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest.class, io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest.Builder.class);
    }

    public static final int MESSAGES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList messages_;
    /**
     * <code>repeated string messages = 1;</code>
     * @return A list containing the messages.
     */
    public com.google.protobuf.ProtocolStringList
        getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated string messages = 1;</code>
     * @return The count of messages.
     */
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated string messages = 1;</code>
     * @param index The index of the element to return.
     * @return The messages at the given index.
     */
    public java.lang.String getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated string messages = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the messages at the given index.
     */
    public com.google.protobuf.ByteString
        getMessagesBytes(int index) {
      return messages_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, messages_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < messages_.size(); i++) {
          dataSize += computeStringSizeNoTag(messages_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMessagesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest)) {
        return super.equals(obj);
      }
      io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest other = (io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request message containing an array of strings.
     * </pre>
     *
     * Protobuf type {@code io.debezium.server.iceberg.rpc.RecordIngestRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.debezium.server.iceberg.rpc.RecordIngestRequest)
        io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest.class, io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest.Builder.class);
      }

      // Construct using io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_descriptor;
      }

      @java.lang.Override
      public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest getDefaultInstanceForType() {
        return io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest build() {
        io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest buildPartial() {
        io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest result = new io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest result) {
        if (((bitField0_ & 0x00000001) != 0)) {
          messages_ = messages_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messages_ = messages_;
      }

      private void buildPartial0(io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest) {
          return mergeFrom((io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest other) {
        if (other == io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest.getDefaultInstance()) return this;
        if (!other.messages_.isEmpty()) {
          if (messages_.isEmpty()) {
            messages_ = other.messages_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessagesIsMutable();
            messages_.addAll(other.messages_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureMessagesIsMutable();
                messages_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new com.google.protobuf.LazyStringArrayList(messages_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @return A list containing the messages.
       */
      public com.google.protobuf.ProtocolStringList
          getMessagesList() {
        return messages_.getUnmodifiableView();
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @return The count of messages.
       */
      public int getMessagesCount() {
        return messages_.size();
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @param index The index of the element to return.
       * @return The messages at the given index.
       */
      public java.lang.String getMessages(int index) {
        return messages_.get(index);
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the messages at the given index.
       */
      public com.google.protobuf.ByteString
          getMessagesBytes(int index) {
        return messages_.getByteString(index);
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @param index The index to set the value at.
       * @param value The messages to set.
       * @return This builder for chaining.
       */
      public Builder setMessages(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMessagesIsMutable();
        messages_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @param value The messages to add.
       * @return This builder for chaining.
       */
      public Builder addMessages(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @param values The messages to add.
       * @return This builder for chaining.
       */
      public Builder addAllMessages(
          java.lang.Iterable<java.lang.String> values) {
        ensureMessagesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messages_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessages() {
        messages_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string messages = 1;</code>
       * @param value The bytes of the messages to add.
       * @return This builder for chaining.
       */
      public Builder addMessagesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureMessagesIsMutable();
        messages_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.debezium.server.iceberg.rpc.RecordIngestRequest)
    }

    // @@protoc_insertion_point(class_scope:io.debezium.server.iceberg.rpc.RecordIngestRequest)
    private static final io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest();
    }

    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordIngestRequest>
        PARSER = new com.google.protobuf.AbstractParser<RecordIngestRequest>() {
      @java.lang.Override
      public RecordIngestRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RecordIngestRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordIngestRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RecordIngestResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.debezium.server.iceberg.rpc.RecordIngestResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    java.lang.String getResult();
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * <pre>
   * The response message with a confirmation string.
   * </pre>
   *
   * Protobuf type {@code io.debezium.server.iceberg.rpc.RecordIngestResponse}
   */
  public static final class RecordIngestResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.debezium.server.iceberg.rpc.RecordIngestResponse)
      RecordIngestResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordIngestResponse.newBuilder() to construct.
    private RecordIngestResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordIngestResponse() {
      result_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecordIngestResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse.class, io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object result_ = "";
    /**
     * <code>string result = 1;</code>
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string result = 1;</code>
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse)) {
        return super.equals(obj);
      }
      io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse other = (io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse) obj;

      if (!getResult()
          .equals(other.getResult())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response message with a confirmation string.
     * </pre>
     *
     * Protobuf type {@code io.debezium.server.iceberg.rpc.RecordIngestResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.debezium.server.iceberg.rpc.RecordIngestResponse)
        io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse.class, io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse.Builder.class);
      }

      // Construct using io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        result_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.debezium.server.iceberg.rpc.RecordIngest.internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_descriptor;
      }

      @java.lang.Override
      public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse getDefaultInstanceForType() {
        return io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse build() {
        io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse buildPartial() {
        io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse result = new io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.result_ = result_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse) {
          return mergeFrom((io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse other) {
        if (other == io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse.getDefaultInstance()) return this;
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                result_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object result_ = "";
      /**
       * <code>string result = 1;</code>
       * @return The result.
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       * @return The bytes for result.
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        result_ = getDefaultInstance().getResult();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       * @param value The bytes for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        result_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.debezium.server.iceberg.rpc.RecordIngestResponse)
    }

    // @@protoc_insertion_point(class_scope:io.debezium.server.iceberg.rpc.RecordIngestResponse)
    private static final io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse();
    }

    public static io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordIngestResponse>
        PARSER = new com.google.protobuf.AbstractParser<RecordIngestResponse>() {
      @java.lang.Override
      public RecordIngestResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RecordIngestResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordIngestResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.debezium.server.iceberg.rpc.RecordIngest.RecordIngestResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023record_ingest.proto\022\036io.debezium.serve" +
      "r.iceberg.rpc\"\'\n\023RecordIngestRequest\022\020\n\010" +
      "messages\030\001 \003(\t\"&\n\024RecordIngestResponse\022\016" +
      "\n\006result\030\001 \001(\t2\217\001\n\023RecordIngestService\022x" +
      "\n\013SendRecords\0223.io.debezium.server.icebe" +
      "rg.rpc.RecordIngestRequest\0324.io.debezium" +
      ".server.iceberg.rpc.RecordIngestResponse" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_debezium_server_iceberg_rpc_RecordIngestRequest_descriptor,
        new java.lang.String[] { "Messages", });
    internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_debezium_server_iceberg_rpc_RecordIngestResponse_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
