name: Olake Driver Build And Release
on:
  workflow_dispatch:
    inputs:
      driver:
        description: "Driver to build"
        required: true
      version:
        description: "Version to release"
        required: true
  workflow_call:
    inputs:
      driver:
        description: "Driver to build"
        required: true
        type: string
        default: ""
      version:
        description: "Version to release"
        required: true
        type: string
        default: ""

jobs:
  publish_drivers:
    name: Publish driver ${{ github.event.inputs.driver }} [manual]
    environment: Publish Driver
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DHID: ${{ secrets.DOCKER_REPO || 'olakego' }}
      DRIVER: ${{ inputs.driver || github.event.inputs.driver || 'mongodb' }}
      VERSION: ${{ inputs.version || github.event.inputs.version || 'v0.0.0.dev' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Verify Docker login
        run: |
          if [ -z "$DOCKER_LOGIN" ]; then
            echo "❌ DOCKER_LOGIN is not set"
          else
            echo "✅ DOCKER_LOGIN is set"
          fi
          
          if [ -z "$DOCKER_PASSWORD" ]; then
            echo "❌ DOCKER_PASSWORD is not set"
          else
            echo "✅ DOCKER_PASSWORD is set"
          fi
          
          echo "DOCKER_REPO=$DOCKER_REPO"
          echo "DHID=$DHID"
          echo "DRIVER=$DRIVER"
          echo "VERSION=$VERSION"

      - name: Set Driver
        run: echo "DRIVER=${{ env.DRIVER }}" >> $GITHUB_ENV
      - name: Set VERSION
        run: echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV
      - name: Show VERSION
        run: echo "Building driver $DRIVER with version $VERSION"
      - name: Run Release tool
        run: |
          chmod +x ./release-tool.sh
          ./release-tool.sh
        shell: bash