name: Performance Test Postgres

on:
  pull_request:
    branches: 
     - main
    paths:
     - '**'
    types: [opened, synchronize, reopened]

jobs:
  performance-test:
    if: github.base_ref == 'main' && github.head_ref == 'staging'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      # - name: Set up go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.22'

      - name: Set ENV Variables
        env:
          PERF: ${{ secrets.PERF }}
        run: |
          if [ -z "${{ secrets.PERF }}" ]; then
            echo "ERROR: PERF secret not found in GitHub Secrets."
            exit 1
          fi
          
          # Create a temporary env file that our script will use
          echo "PERF=${PERF}" > .env
          
      - name: Setup Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh > /dev/null 2>&1
          sudo usermod -aG docker $USER
          sudo chmod 666 /var/run/docker.sock

      - name: Run Performance Test
        run: |
          echo "Running Performance Test"
          chmod +x performance/performance_test.sh
          ./performance/performance_test.sh

      - name: Check Test Results
        if: failure()
        run: |
          echo "Performance test failed. Please check the logs for more details."
          exit 1